[default]
DEBUG = false
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [
    "project.ext.database:init_app",
    "project.ext.commands:init_app",
    "project.restapi.user:init_app",
    "project.restapi.cinema:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_TRACK_MODIFICATIONS = false

[testing]

[production]
