[default]
DEBUG = false
SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite'
SECRET_KEY = "manguinha"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [

]

[development]
DEBUG = true

[testing]
SQLALCHEMY_DATABASE_URI = 'sqlite:///testing.db'

[production]
SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'